<a href="https://colab.research.google.com/github/subhajit404/RNN/blob/main/Rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('qoute_dataset.csv')

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes = df['quote']

In [ ]:
quotes = quotes.str.lower()

In [ ]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
df['quote']

0       “The world as we have created it is a process ...
1       “It is our choices, Harry, that show what we t...
2       “There are only two ways to live your life. On...
3       “The person, be it gentleman or lady, who has ...
4       “Imperfection is beauty, madness is genius and...
                              ...
3033        The past beats inside me like a second heart.
3034    Damn, Claire. Warn a guy before you do a face-...
3035    Can you be a girl for a few seconds?""I'm alwa...
3036    That's what fiction is for. It's for getting a...
3037    If we have no peace, it is because we have for...
Name: quote, Length: 3038, dtype: object

In [ ]:
quotes = quotes.str.replace(r'[^\w\s]', '', regex=True)

In [ ]:
quotes

0       the world as we have created it is a process o...
1       it is our choices harry that show what we trul...
2       there are only two ways to live your life one ...
3       the person be it gentleman or lady who has not...
4       imperfection is beauty madness is genius and i...
                              ...
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [ ]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.4.0)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.7.0)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (7.36.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from tensorflow) (80.10.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.83.1)
Requirement already satisfied: keras>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.1.3)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.6.0)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-manylinux_2_27_x86_64.whl (572.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.9/572.9 MB 761.3 kB/s eta 0:00:00
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.0 MB/s eta 0:00:00
Downloading h5py-3.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 130.1 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 86.8 MB/s eta 0:00:00
Downloading wheel-0.48.0-py3-none-any.whl (33 kB)
Installing collected packages: libclang, flatbuffers, wheel, h5py, google_pasta, astunparse, tensorflow
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0
Successfully installed astunparse-1.6.3 flatbuffers-25.12.19 google_pasta-0.2.0 h5py-3.14.0 libclang-18.1.1 tensorflow-2.21.0 wheel-0.48.0

In [ ]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [ ]:
quotes.str.split().explode().unique().size

8724

In [ ]:
word_idx = tokenizer.word_index
print(len(word_idx))
list(word_idx.items())[:10]

8723

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
sequence = tokenizer.texts_to_sequences(quotes)

In [ ]:
for i in range (3):
    print(quotes[i])

the world as we have created it is a process of our thinking it cannot be changed without changing our thinking
it is our choices harry that show what we truly are far more than our abilities
there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle

In [ ]:
for i in range (3):
    print(quotes[i])

the world as we have created it is a process of our thinking it cannot be changed without changing our thinking
it is our choices harry that show what we truly are far more than our abilities
there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle

In [ ]:
X = []
y = []


for seq in sequence:
    for i in range(1,len(seq)):
        input_seq = seq[:i]
        output_seq = seq[i]
        X.append(input_seq)
        y.append(output_seq)

In [ ]:
X

[[1],
 [1, 62],
 [1, 62, 29],
 [1, 62, 29, 19],
 [1, 62, 29, 19, 16],
 [1, 62, 29, 19, 16, 937],
 [1, 62, 29, 19, 16, 937, 10],
 [1, 62, 29, 19, 16, 937, 10, 7],
 [1, 62, 29, 19, 16, 937, 10, 7, 5],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70, 285],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70, 285, 10],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70, 285, 10, 146],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70, 285, 10, 146, 12],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70, 285, 10, 146, 12, 804],
 [1, 62, 29, 19, 16, 937, 10, 7, 5, 1143, 8, 70, 285, 10, 146, 12, 804, 105],
 [1,
  62,
  29,
  19,
  16,
  937,
  10,
  7,
  5,
  1143,
  8,
  70,
  285,
  10,
  146,
  12,
  804,
  105,
  741],
 [1,
  62,
  29,
  19,
  16,
  937,
  10,
  7,
  5,
  1143,
  8,
  70,
  285,
  10,
  146,
  12,
  804,
  105,
  741,
  70],
 [10],
 [10, 7],
 [10, 7, 70],
 [10, 7, 70, 863],
 [10, 7, 70, 863, 373],
 [10, 7, 70, 863, 373, 9],
 [10, 7, 70, 863, 373, 9, 432],
 [10, 7, 70, 863, 373, 9, 432, 21],
 [10, 7, 70, 863, 373, 9, 432, 21, 19],
 [10, 7, 70, 863, 373, 9, 432, 21, 19, 464],
 [10, 7, 70, 863, 373, 9, 432, 21, 19, 464, 14],
 [10, 7, 70, 863, 373, 9, 432, 21, 19, 464, 14, 296],
 [10, 7, 70, 863, 373, 9, 432, 21, 19, 464, 14, 296, 52],
 [10, 7, 70, 863, 373, 9, 432, 21, 19, 464, 14, 296, 52, 54],
 [10, 7, 70, 863, 373, 9, 432, 21, 19, 464, 14, 296, 52, 54, 70],
 [42],
 [42, 14],
 [42, 14, 53],
 [42, 14, 53, 201],
 [42, 14, 53, 201, 706],
 [42, 14, 53, 201, 706, 3],
 [42, 14, 53, 201, 706, 3, 81],
 [42, 14, 53, 201, 706, 3, 81, 15],
 [42, 14, 53, 201, 706, 3, 81, 15, 35],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312, 95],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312, 95, 7],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312, 95, 7, 5],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312, 95, 7, 5, 1031],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312, 95, 7, 5, 1031, 1],
 [42, 14, 53, 201, 706, 3, 81, 15, 35, 37, 7, 29, 312, 95, 7, 5, 1031, 1, 103],
 [42,
  14,
  53,
  201,
  706,
  3,
  81,
  15,
  35,
  37,
  7,
  29,
  312,
  95,
  7,
  5,
  1031,
  1,
  103,
  7],
 [42,
  14,
  53,
  201,
  706,
  3,
  81,
  15,
  35,
  37,
  7,
  29,
  312,
  95,
  7,
  5,
  1031,
  1,
  103,
  7,
  29],
 [42,
  14,
  53,
  201,
  706,
  3,
  81,
  15,
  35,
  37,
  7,
  29,
  312,
  95,
  7,
  5,
  1031,
  1,
  103,
  7,
  29,
  312],
 [42,
  14,
  53,
  201,
  706,
  3,
  81,
  15,
  35,
  37,
  7,
  29,
  312,
  95,
  7,
  5,
  1031,
  1,
  103,
  7,
  29,
  312,
  128],
 [42,
  14,
  53,
  201,
  706,
  3,
  81,
  15,
  35,
  37,
  7,
  29,
  312,
  95,
  7,
  5,
  1031,
  1,
  103,
  7,
  29,
  312,
  128,
  7],
 [42,
  14,
  53,
  201,
  706,
  3,
  81,
  15,
  35,
  37,
  7,
  29,
  312,
  95,
  7,
  5,
  1031,
  1,
  103,
  7,
  29,
  312,
  128,
  7,
  5],
 [1],
 [1, 116],
 [1, 116, 12],
 [1, 116, 12, 10],
 [1, 116, 12, 10, 2428],
 [1, 116, 12, 10, 2428, 33],
 [1, 116, 12, 10, 2428, 33, 1032],
 [1, 116, 12, 10, 2428, 33, 1032, 31],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597, 11],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597, 11, 5],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597, 11, 5, 74],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597, 11, 5, 74, 1320],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597, 11, 5, 74, 1320, 120],
 [1, 116, 12, 10, 2428, 33, 1032, 31, 82, 13, 597, 11, 5, 74, 1320, 120, 12],
 [1,
  116,
  12,
  10,
  2428,
  33,
  1032,
  31,
  82,
  13,
  597,
  11,
  5,
  74,
  1320,
  120,
  12,
  2429],
 [2430],
 [2430, 7],
 [2430, 7, 297],
 [2430, 7, 297, 742],
 [2430, 7, 297, 742, 7],
 [2430, 7, 297, 742, 7, 634],
 [2430, 7, 297, 742, 7, 634, 4],
 [2430, 7, 297, 742, 7, 634, 4, 39],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144, 3],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144, 3, 12],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144, 3, 12, 677],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144, 3, 12, 677, 1321],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144, 3, 12, 677, 1321, 54],
 [2430, 7, 297, 742, 7, 634, 4, 39, 144, 3, 12, 677, 1321, 54, 677],
 [260],
 [260, 13],
 [260, 13, 3],
 [260, 13, 3, 202],
 [260, 13, 3, 202, 5],
 [260, 13, 3, 202, 5, 92],
 [260, 13, 3, 202, 5, 92, 8],
 [260, 13, 3, 202, 5, 92, 8, 433],
 [260, 13, 3, 202, 5, 92, 8, 433, 283],
 [260, 13, 3, 202, 5, 92, 8, 433, 283, 202],
 [260, 13, 3, 202, 5, 92, 8, 433, 283, 202, 5],
 [260, 13, 3, 202, 5, 92, 8, 433, 283, 202, 5, 92],
 [260, 13, 3, 202, 5, 92, 8, 433, 283, 202, 5, 92, 8],
 [10],
 [10, 7],
 [10, 7, 144],
 [10, 7, 144, 3],
 [10, 7, 144, 3, 12],
 [10, 7, 144, 3, 12, 1322],
 [10, 7, 144, 3, 12, 1322, 17],
 [10, 7, 144, 3, 12, 1322, 17, 21],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3, 12],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3, 12, 177],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3, 12, 177, 17],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3, 12, 177, 17, 21],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3, 12, 177, 17, 21, 2],
 [10, 7, 144, 3, 12, 1322, 17, 21, 2, 14, 54, 3, 12, 177, 17, 21, 2, 14],
 [6],
 [6, 16],
 [6, 16, 13],
 [6, 16, 13, 1323],
 [6, 16, 13, 1323, 173],
 [6, 16, 13, 1323, 173, 51],
 [6, 16, 13, 1323, 173, 51, 415],
 [6, 16, 13, 1323, 173, 51, 415, 2431],
 [6, 16, 13, 1323, 173, 51, 415, 2431, 706],
 [6, 16, 13, 1323, 173, 51, 415, 2431, 706, 9],
 [6, 16, 13, 1323, 173, 51, 415, 2431, 706, 9, 313],
 [5],
 [5, 183],
 [5, 183, 7],
 [5, 183, 7, 40],
 [5, 183, 7, 40, 5],
 [5, 183, 7, 40, 5, 805],
 [5, 183, 7, 40, 5, 805, 1324],
 [5, 183, 7, 40, 5, 805, 1324, 2],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321, 10],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321, 10, 7],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321, 10, 7, 169],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321, 10, 7, 169, 39],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321, 10, 7, 169, 39, 11],
 [5, 183, 7, 40, 5, 805, 1324, 2, 47, 50, 59, 321, 10, 7, 169, 39, 11, 635],
 [5],
 [5, 111],
 [5, 111, 105],
 [5, 111, 105, 1033],
 [5, 111, 105, 1033, 7],
 [5, 111, 105, 1033, 7, 40],
 [5, 111, 105, 1033, 7, 40, 2],
 [5, 111, 105, 1033, 7, 40, 2, 50],
 [56],
 [56, 35],
 [56, 35, 7],
 [56, 35, 7, 21],
 [56, 35, 7, 21, 2],
 [56, 35, 7, 21, 2, 65],
 [56, 35, 7, 21, 2, 65, 10],
 [56, 35, 7, 21, 2, 65, 10, 48],
 [56, 35, 7, 21, 2, 65, 10, 48, 184],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132, 3],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132, 3, 744],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132, 3, 744, 58],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132, 3, 744, 58, 126],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132, 3, 744, 58, 126, 39],
 [56, 35, 7, 21, 2, 65, 10, 48, 184, 21, 85, 132, 3, 744, 58, 126, 39, 5],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2,
  147],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2,
  147,
  128],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2,
  147,
  128,
  223],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2,
  147,
  128,
  223,
  15],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2,
  147,
  128,
  223,
  15,
  161],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,
  465,
  59,
  85,
  132,
  3,
  744,
  10,
  58,
  517,
  28,
  12,
  15,
  211,
  745,
  518,
  40,
  10,
  806,
  18,
  51,
  155,
  91,
  134,
  91,
  79,
  1,
  222,
  9,
  275,
  23,
  2,
  147,
  128,
  223,
  15,
  161,
  159],
 [56,
  35,
  7,
  21,
  2,
  65,
  10,
  48,
  184,
  21,
  85,
  132,
  3,
  744,
  58,
  126,
  39,
  5,
  1913,
  176,
  18,
  1,
  74,
  210,
  7,
  2,
  96,
  3,

In [ ]:
y

[62,
 29,
 19,
 16,
 937,
 10,
 7,
 5,
 1143,
 8,
 70,
 285,
 10,
 146,
 12,
 804,
 105,
 741,
 70,
 285,
 7,
 70,
 863,
 373,
 9,
 432,
 21,
 19,
 464,
 14,
 296,
 52,
 54,
 70,
 2427,
 14,
 53,
 201,
 706,
 3,
 81,
 15,
 35,
 37,
 7,
 29,
 312,
 95,
 7,
 5,
 1031,
 1,
 103,
 7,
 29,
 312,
 128,
 7,
 5,
 1031,
 116,
 12,
 10,
 2428,
 33,
 1032,
 31,
 82,
 13,
 597,
 11,
 5,
 74,
 1320,
 120,
 12,
 2429,
 329,
 7,
 297,
 742,
 7,
 634,
 4,
 39,
 144,
 3,
 12,
 677,
 1321,
 54,
 677,
 743,
 13,
 3,
 202,
 5,
 92,
 8,
 433,
 283,
 202,
 5,
 92,
 8,
 516,
 7,
 144,
 3,
 12,
 1322,
 17,
 21,
 2,
 14,
 54,
 3,
 12,
 177,
 17,
 21,
 2,
 14,
 13,
 16,
 13,
 1323,
 173,
 51,
 415,
 2431,
 706,
 9,
 313,
 273,
 183,
 7,
 40,
 5,
 805,
 1324,
 2,
 47,
 50,
 59,
 321,
 10,
 7,
 169,
 39,
 11,
 635,
 480,
 111,
 105,
 1033,
 7,
 40,
 2,
 50,
 274,
 35,
 7,
 21,
 2,
 65,
 10,
 48,
 184,
 21,
 85,
 132,
 3,
 744,
 58,
 126,
 39,
 5,
 1913,
 176,
 18,
 1,
 74,
 210,
 7,
 2,
 96,
 3,
 465,
 59,
 85,
 132,
 3,
 744,
 10,
 58,
 517,
 28,
 12,
 15,
 211,
 745,
 518,
 40,
 10,
 806,
 18,
 51,
 155,
 91,
 134,
 91,
 79,
 1,
 222,
 9,
 275,
 23,
 2,
 147,
 128,
 223,
 15,
 161,
 159,
 211,
 41,
 102,
 79,
 8,
 49,
 388,
 155,
 2432,
 65,
 1,
 159,
 211,
 11,
 1,
 62,
 29,
 17,
 1325,
 168,
 745,
 134,
 4,
 79,
 88,
 4,
 807,
 6,
 276,
 3,
 118,
 10,
 117,
 8,
 49,
 481,
 416,
 106,
 22,
 8,
 49,
 14,
 132,
 3,
 389,
 15,
 94,
 18,
 2,
 124,
 135,
 58,
 55,
 20,
 2,
 135,
 58,
 207,
 47,
 113,
 15,
 2433,
 207,
 47,
 113,
 9,
 417,
 31,
 214,
 2,
 255,
 4,
 9,
 418,
 17,
 128,
 51,
 55,
 2,
 678,
 187,
 165,
 268,
 85,
 1034,
 678,
 45,
 128,
 178,
 264,
 342,
 43,
 4,
 69,
 69,
 69,
 129,
 11,
 100,
 55,
 20,
 2,
 41,
 89,
 31,
 28,
 2434,
 46,
 178,
 15,
 307,
 419,
 178,
 15,
 1547,
 58,
 4,
 117,
 1548,
 178,
 808,
 55,
 746,
 5,
 194,
 93,
 4,
 188,
 46,
 106,
 3,
 293,
 66,
 343,
 5,
 151,
 636,
 8,
 864,
 3,
 314,
 58,
 3,
 70,
 747,
 18,
 51,
 29,
 106,
 3,
 314,
 58,
 3,
 70,
 211,
 2,
 124,
 938,
 10,
 3,
 5,
 939,
 466,
 265,
 2,
 41,
 224,
 10,
 100,
 137,
 13,
 12,
 77,
 180,
 77,
 266,
 33,
 77,
 53,
 76,
 177,
 185,
 76,
 137,
 24,
 170,
 18,
 20,
 76,
 227,
 2,
 148,
 21,
 171,
 598,
 420,
 13,
 2435,
 402,
 403,
 4,
 1,
 201,
 8,
 2,
 137,
 47,
 12,
 344,
 269,
 18,
 20,
 76,
 25,
 65,
 2,
 298,
 865,
 2,
 3,
 64,
 1035,
 4,
 940,
 3,
 130,
 189,
 4,
 354,
 390,
 342,
 941,
 77,
 4,
 135,
 77,
 1,
 117,
 2,
 25,
 76,
 137,
 13,
 12,
 285,
 66,
 2,
 90,
 450,
 8,
 1,
 111,
 18,
 76,
 28,
 135,
 2,
 5,
 210,
 8,
 77,
 9,
 76,
 277,
 2,
 25,
 2436,
 94,
 46,
 41,
 286,
 77,
 41,
 156,
 77,
 41,
 1914,
 4,
 41,
 451,
 52,
 54,
 76,
 25,
 135,
 293,
 27,
 76,
 214,
 2,
 191,
 102,
 77,
 50,
 27,
 76,
 214,
 2,
 434,
 4,
 571,
 77,
 27,
 420,
 13,
 42,
 40,
 809,
 10,
 1549,
 58,
 1,
 810,
 1915,
 599,
 7,
 5,
 600,
 1916,
 11,
 234,
 137,
 13,
 16,
 330,
 138,
 6,
 2437,
 3,
 79,
 18,
 6,
 64,
 6,
 16,
 1917,
 58,
 138,
 6,
 748,
 3,
 12,
 811,
 8,
 24,
 7,
 13,
 276,
 39,
 749,
 1,
 811,
 8,
 493,
 7,
 13,
 1918,
 39,
 749,
 1,
 811,
 8,
 601,
 7,
 13,
 2438,
 39,
 749,
 4,
 1,
 811,
 8,
 35,
 7,
 13,
 215,
 39,
 749,
 7,
 13,
 5,
 866,
 8,
 24,
 18,
 5,
 866,
 8,
 435,
 9,
 214,
 750,
 2439,
 211,
 74,
 114,
 4,
 5,
 2440,
 867,
 56,
 7,
 1,
 1550,
 35,
 7,
 21,
 322,
 3,
 73,
 235,
 19,
 14,
 354,
 103,
 1036,
 24,
 2,
 105,
 364,
 59,
 33,
 27,
 33,
 68,
 138,
 6,
 24,
 2,
 572,
 105,
 812,
 33,
 868,
 6,
 24,
 2,
 11,
 56,
 78,
 55,
 6,
 30,
 13,
 50,
 145,
 103,
 78,
 8,
 391,
 18,
 56,
 11,
 121,
 42,
 7,
 48,
 6,
 33,
 2,
 46,
 1326,
 9,
 15,
 315,
 247,
 26,
 751,
 7,
 26,
 315,
 46,
 1326,
 9,
 27,
 6,
 232,
 679,
 15,
 225,
 404,
 90,
 637,
 2,
 14,
 752,
 2,
 240,
 1919,
 1327,
 8,
 196,
 2,
 707,
 44,
 2,
 16,
 48,
 67,
 3,
 24,
 49,
 31,
 573,
 942,
 11,
 1551,
 25,
 65,
 2,
 5,
 1552,
 120,
 388,
 64,
 9,
 942,
 11,
 5,
 1920,
 25,
 65,
 2,
 5,
 813,
 7,
 11,
 1,
 680,
 8,
 1,
 1553,
 4,
 10,
 137,
 12,
 600,
 68,
 67,
 3,
 67,
 3,
 135,
 5,
 329,
 33,
 1554,
 1553,
 5,
 467,
 680,
 2,
 14,
 2,
 9,
 7,
 1921,
 54,
 161,
 42,
 7,
 48,
 37,
 392,
 31,
 7,
 2441,
 54,
 2,
 2,
 57,
 15,
 331,
 3,
 12,
 574,
 125,
 49,
 681,
 638,
 20,
 2,
 57,
 49,
 3,
 12,
 52,
 574,
 125,
 49,
 52,
 681,
 638,
 7,
 374,
 3,
 81,
 105,
 1555,
 45,
 83,
 468,
 2,
 81,
 46,
 2442,
 9,
 2,
 256,
 29,
 168,
 13,
 16,
 421,
 45,
 22,
 11,
 121,
 814,
 2,
 678,
 63,
 1922,
 28,
 96,
 2,
 68,
 5,
 3,
 1557,
 494,
 28,
 96,
 2,
 1328,
 74,
 93,
 66,
 299,
 27,
 10,
 1144,
 2,
 2,
 133,
 48,
 208,
 52,
 9,
 2,
 125,
 1,
 52,
 61,
 2,
 28,
 50,
 1,
 52,
 9,
 2,
 203,
 1,
 52,
 639,
 207,
 79,
 482,
 10,
 7,
 943,
 217,
 15,
 307,
 373,
 18,
 174,
 43,
 279,
 127,
 9,
 268,
 9,
 10,
 7,
 13,
 212,
 176,
 7,
 237,
 7,
 132,
 3,
 286,
 2,
 2,
 51,
 206,
 3,
 113,
 1,
 222,
 332,
 405,
 17,
 22,
 8,
 73,
 25,
 30,
 151,
 61,
 18,
 19,
 25,
 30,
 294,
 61,
 23,
 151,
 24,
 1,
 2443,
 166,
 215,
 7,
 18,
 1,
 393,
 151,
 708,
 2,
 164,
 7,
 24,
 18,
 5,
 140,
 1329,
 148,
 4,
 89,
 165,
 286,
 125,
 3,
 50,
 86,
 13,
 209,
 519,
 25,
 50,
 1,
 333,
 7,
 3,
 224,
 16,
 69,
 1558,
 9,
 1559,
 28,
 12,
 5,
 195,
 8,
 544,
 7,
 47,
 88,
 602,
 3,
 12,
 ...]

In [ ]:
len(X)

85212

In [ ]:
len(y)

85212

In [ ]:
max_len= max(len(x) for x in X)
max_len

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
X_pad = pad_sequences(X,maxlen=max_len,padding='pre')

In [ ]:
y= np.array(y)

In [ ]:
y.shape

(85212,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y,num_classes= vocab_size)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

In [ ]:
emb_dim = 50
rnn_units = 128

In [ ]:
rnn_model =Sequential()
rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=emb_dim,input_length=max_len)
)

rnn_model.add(
    SimpleRNN(units=rnn_units)
)
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

In [ ]:
rnn_model.compile(
    optimizer='adam',
    loss= 'categorical_crossentropy',
    metrics = ['accuracy']
    )

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=emb_dim,input_length=max_len)
)

lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [ ]:
lstm_model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
rnn_model.fit(X_pad,y_one_hot ,epochs=10,batch_size=128,verbose=1)

Epoch 1/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 156s 233ms/step - accuracy: 0.0455 - loss: 6.6704
Epoch 2/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.0814 - loss: 6.0636
Epoch 3/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.1064 - loss: 5.7049
Epoch 4/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.1226 - loss: 5.4113
Epoch 5/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.1357 - loss: 5.1568
Epoch 6/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.1485 - loss: 4.9267
Epoch 7/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.1635 - loss: 4.7107
Epoch 8/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 231ms/step - accuracy: 0.1794 - loss: 4.5114
Epoch 9/10
666/666 ━━━━━━━━━━━━━━━━━━━━ 154s 232ms/step - accuracy: 0.2001 - loss: 4.3230
Epoch 10/10
633/666 ━━━━━━━━━━━━━━━━━━━━ 7s 231ms/step - accuracy: 0.2291 - loss: 4.0623